# Generated by Django 5.2.9 on 2026-01-04 20:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('popularity', models.SmallIntegerField(blank=True, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('spotify_id', models.CharField(max_length=22, unique=True)),
                ('spotify_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('popularity', models.SmallIntegerField(blank=True, null=True)),
                ('spotify_id', models.CharField(max_length=22, unique=True)),
                ('spotify_url', models.CharField(max_length=255)),
                ('artists', models.ManyToManyField(related_name='albums', to='core.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('explicit', models.BooleanField(default=False)),
                ('popularity', models.SmallIntegerField(blank=True, null=True)),
                ('spotify_id', models.CharField(max_length=22, unique=True)),
                ('spotify_url', models.CharField(max_length=255)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='core.album')),
                ('artists', models.ManyToManyField(related_name='tracks', to='core.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
