# Generated by Django 5.2.9 on 2026-01-04 20:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_track_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('played_at', models.DateTimeField()),
                ('platform', models.CharField(max_length=20)),
                ('ms_played', models.PositiveIntegerField()),
                ('spotify_track_id', models.CharField(max_length=22)),
                ('reason_start', models.CharField(max_length=20)),
                ('reason_end', models.CharField(max_length=20)),
                ('shuffle', models.BooleanField()),
                ('skipped', models.BooleanField()),
                ('offline', models.BooleanField(null=True)),
                ('offline_timestamp', models.PositiveBigIntegerField(null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
