# Generated by Django 5.2.9 on 2026-01-07 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_listeninghistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listeninghistory',
            constraint=models.UniqueConstraint(fields=('user', 'played_at', 'ms_played'), name='unique_listeninghistory_user_played_at_ms'),
        ),
    ]
