# Generated by Django 5.2.9 on 2026-01-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listeninghistory_unique_listeninghistory_user_played_at_ms'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listeninghistory',
            name='unique_listeninghistory_user_played_at_ms',
        ),
    ]
