# Generated by Django 5.2.9 on 2026-01-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_listeninghistory_unique_listeninghistory_user_played_at_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninghistory',
            name='ip_addr',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
