# Generated by Django 5.2.9 on 2026-01-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_listeninghistory_ip_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninghistory',
            name='ip_addr',
            field=models.GenericIPAddressField(),
        ),
    ]
