# Generated by Django 5.2.9 on 2026-01-04 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedSpotifyListen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ts', models.DateTimeField()),
                ('platform', models.CharField(max_length=20)),
                ('ms_played', models.PositiveIntegerField()),
                ('spotify_track_id', models.CharField(max_length=22)),
                ('reason_start', models.CharField(max_length=20)),
                ('reason_end', models.CharField(max_length=20)),
                ('shuffle', models.BooleanField()),
                ('skipped', models.BooleanField()),
                ('offline', models.BooleanField()),
                ('offline_timestamp', models.PositiveBigIntegerField()),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_listens', to='imports.importjob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
