# Generated by Django 5.2.9 on 2026-01-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_parsedspotifylisten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedspotifylisten',
            name='offline_timestamp',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
