# Generated by Django 5.2.9 on 2026-01-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_alter_parsedspotifylisten_offline_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedspotifylisten',
            name='offline',
            field=models.BooleanField(null=True),
        ),
    ]
