# Generated by Django 5.2.9 on 2026-01-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_alter_parsedspotifylisten_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedspotifylisten',
            name='ip_addr',
            field=models.GenericIPAddressField(default=''),
            preserve_default=False,
        ),
    ]
